Add Heal Combos for Scholar
Nik-Potokar/XIVSlothCombo pull request #1013
Opened 2022-09-30 15:04 UTC by Hazado

Adds some healing combos for the Scholar.

Fairy Combo - Whispering Dawn primary 
Fey Illumination -> Fey Blessing -> Whispering Dawn

AOE - Succor Primary 
(Standard Aethorflow and Lucid Dreaming options) - Indomitability (When you have Aethor) -> Succor

Single Target - Physick Primary 
(Standard Aethorflow and Lucid Dreaming options) - Target check ( Soft->Hard->Self) - Adloquim (when they dont have Galvanize or Target HP below whatever percentage you set in options) -> Lustrate (When you have Aethor and the target HP is below whatever percentage you set in options) -> Physick

2022-10-04 23:58 UTC, Tartarga requested changes
There are a few spots I see where you can remove LevelChecked. ActionReady checks for level and cooldown status as an "all in one" check. If I used github correctly, I've marked the ones I see

2022-10-04 23:58 UTC, Tartarga commented on XIVSlothCombo/Combos/PvE/SCH.cs
> +                        LevelChecked(Indomitability) &&
ActionReady includes the level checking, you can remove the extra LevelChecked

2022-10-04 23:58 UTC, Tartarga commented on XIVSlothCombo/Combos/PvE/SCH.cs
> +
Same here, you can remove the LevelChecked's on the Fey's

2022-10-04 23:58 UTC, Tartarga commented on XIVSlothCombo/Combos/PvE/SCH.cs
> +                        LevelChecked(Lustrate) &&
Another LevelChecked can be removed

2022-10-05 00:31 UTC, k-kz commented
I tried to nab those quickly in the web editor but apparently the diff had a hard time with it so have reverted for the time being.

2022-10-05 00:46 UTC, Tartarga commented
> I tried to nab those quickly in the web editor but apparently the diff had a hard time with it so have reverted for the time being.

I believe this branch was made when SCH had the linux line breaks. @Hazado just needs to merge in main to refresh

2022-10-05 01:02 UTC, Hazado commented
Ill remove the requested stuff and push and update later tonight. Do you want me to change to windows line endings as well?

2022-10-05 04:10 UTC, Hazado commented
Changes made

2022-10-05 10:54 UTC, Daemeous approved these changes
Not sure how much my opinion counts for but these look like good changes, basically what I already had setup via reaction but with some smarter additions in there with Lucid and Aether usage.

This would, in a round about way, resolve #871 as it gives the option to turn Physick into Adloquium that would default to Physick if you were synced below 30.

2022-10-06 18:19 UTC, Hazado commented
Rebased to remove conflict with Main

2022-10-06 18:27 UTC, Daemeous commented
Hmm, it looks like line endings are a problem again, since the main is now properly back on CRLF endings and your file looks like it's back to LF.

2022-10-06 18:30 UTC, Hazado commented
> Hmm, it looks like line endings are a problem again, since the main is now properly back on CRLF endings and your file looks like it's back to LF.

Fixed now.

2022-10-06 18:33 UTC, Daemeous commented
Strangely that doesn't seem to have done it...Perhaps pulling from the Sloth main would fix it?

2022-10-06 18:55 UTC, Daemeous commented
I can see how hard you're trying but something is wrong here. I just pulled your code and your line endings are indeed correctly CRLF...Github should not be showing that false large diff...

2022-10-06 18:58 UTC, Hazado commented
Yeah, Im going to need to leave it alone for a bit...

2022-10-06 19:58 UTC, Hazado commented
Line endings fixed for sure now

2022-10-06 20:00 UTC, Daemeous commented
Champion!

2022-10-07 01:03 UTC, merged