[PLD] Post Rework MP Reserve Feature
Nik-Potokar/XIVSlothCombo pull request #1590
Opened 2024-07-23 17:27 UTC by AustinSumigray

Allows for only spending MP on skills when above a set number. The intended use case is reserving a bit of MP in case of emergency Clemency heals. The triggering pain point is a scenario where you have spent all your MP, and wish to be able to use Clemency as needed, but the combo wishes to spend it on Holy Spirit stacks or similar. You then can't use the combo itself to regain MP. This feature would skip casts of MP-using skills until you had built back up to the reserve value.

2024-07-24 01:54 UTC, Akechi-kun commented
This is very unlikely to be merged. This project doesn't support helping with mitigations or situational issues, it's made to execute a DPS rotation with either 1 button or reduce button bloat to any standards. This PR is just opening the door to start adding in mitigations, and then what's next that follows if this merges is everyone asking for the other Tanks' mitigations to be added, which isn't what this project is aimed for in the first place.

2024-07-24 06:30 UTC, Taurenkey requested changes
This needs a bit of a tweak. Create seperate options for the ST & AoE rather than put them as just one unrelated option.

2024-07-24 16:49 UTC, AustinSumigray commented
> This needs a bit of a tweak. Create seperate options for the ST & AoE rather than put them as just one unrelated option.

Sure, there you go.

2024-07-24 17:03 UTC, AustinSumigray commented
> This is very unlikely to be merged. This project doesn't support helping with mitigations or situational issues, it's made to execute a DPS rotation with either 1 button or reduce button bloat to any standards. This PR is just opening the door to start adding in mitigations, and then what's next that follows if this merges is everyone asking for the other Tanks' mitigations to be added, which isn't what this project is aimed for in the first place.

The option doesn't use your mitigation for you, it just makes it so you can set a limit to how much of the resource you use for it you use on other tasks. A similar option is the Sheltron Option, that lets you set an amount of Oath gauge you want to have before you spend it on Sheltron.

2024-07-25 08:48 UTC, Taurenkey approved these changes

2024-07-31 16:06 UTC, merged